### ISSUE TITLE
Unsatisfiable requirements for Julia  > v1.0.0

### ISSUE THREAD

**Issue by jbmuir** [PieterjanRobbe/GaussianRandomFields.jl#13]
Gaussian Random Fields is apparently locked to v1.0.0 in the main Julia package registry, so you can't download it using add GaussianRandomFields in the package manager. (PS thanks for a great package to the contributors!) 

```
Unsatisfiable requirements detected for package GaussianRandomFields [e4b2fa32]:
 GaussianRandomFields [e4b2fa32] log:
 ├─possible versions are: 1.0.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 1.0.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by PieterjanRobbe** [comment]
Thanks for pointing this out. That should hopefully be fixed once [#18885](https://github.com/JuliaLang/METADATA.jl/pull/18885) gets merged in METADATA. In the mean time, can you checkout GaussianRandomFields#master for development?

**Comment by jbmuir** [comment]
Thanks - currently I'm tracking the master using the URL option in the package manager

**Comment by PieterjanRobbe** [comment]
Whoops, I can draft a new release to see if the issue can be resolved.

**Comment by mattiasvillani** [comment]
I am getting 'Unsatisfiable requirements detected for package FFTW'. Don't want to open a new issue for this in the hope that it is related to the current issue. Here is the output from the package manager:

(v1.3) pkg> add GaussianRandomFields
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package FFTW [7a1cc6ca]:
 FFTW [7a1cc6ca] log:
 ├─possible versions are: [0.1.0-0.1.2, 0.2.0-0.2.4, 0.3.0, 1.0.0-1.0.1, 1.1.0, 1.2.0] or uninstalled
 ├─restricted to versions 1.2.0 by an explicit requirement, leaving only versions 1.2.0
 └─restricted by compatibility requirements with GaussianRandomFields [e4b2fa32] to versions: [0.1.0-0.1.2, 0.2.0-0.2.4, 0.3.0] — no versions left
   └─GaussianRandomFields [e4b2fa32] log:
     ├─possible versions are: 1.1.1 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 1.1.1
I am using Julia 1.3.1 on Linux.

**Comment by devmotion** [comment]
It seems you have installed FFTW 1.2.0 before installing GaussianRandomFields but GaussianRandomFields is not compatible with FFTW >= 1. I've opened a PR that should fix the dependency issues.

**Comment by devmotion** [comment]
@PieterjanRobbe can you register the new version with JuliaRegistrator so that this issue is actually fixed?

**Comment by PieterjanRobbe** [comment]
@devmotion this should be fixed now, right?

**Comment by devmotion** [comment]
Yes, seems version 2.0.0 is now part of the general registry. Thanks!
