### ISSUE TITLE
Update library to later versions of Julia

### ISSUE THREAD

**Issue by la3lma** [PieterjanRobbe/GaussianRandomFields.jl#15]
Hi.
This looks like a vary useful library for generating random fields, but it's not updated to later versions of Julia.  Is there an updated version somewhere, or is this project now abandoned?

**Comment by PieterjanRobbe** [comment]
The latest version (v2.0.0) of GaussianRandomFields was tagged a week ago and is compatible with Julia 1.3 (see #13). Are you experiencing any specific problems?
