### ISSUE TITLE
Links to tutorial and API in README.md are broken

### ISSUE THREAD

**Issue by tkoskela** [PieterjanRobbe/GaussianRandomFields.jl#18]
Both return a file not found error

**Comment by PieterjanRobbe** [comment]
Thanks for pointing that out! The links should work again now, could you please check?

**Comment by tkoskela** [comment]
Yes, they do. Thanks for fixing them so quickly!

**Comment by PieterjanRobbe** [comment]
Hmm but now somehow the pictures do not show up in the Tutorial, let me try to fix this.

**Comment by tkoskela** [comment]
I am getting "File not found" again

**Comment by PieterjanRobbe** [comment]
It should work again now, including the pictures in the tutorial.
