### ISSUE TITLE
Use plot recipes instead of depending on Plots

### ISSUE THREAD

**Issue by giordano** [PieterjanRobbe/GaussianRandomFields.jl#19]
`Plots.jl` is a huge dependency, the fact that `GaussianRandomFields.jl` depends on it makes using your package less attractive.

Have you considered using [plot recipes](https://docs.juliaplots.org/latest/recipes/) instead?  [`RecipesBase.jl`](https://github.com/JuliaPlots/RecipesBase.jl) is a standalone package that doesn't pull gazillion of other packages in turn.

**Comment by PieterjanRobbe** [comment]
Thanks for pointing that out, I'll take a look at `RecipesBase.jl`.

**Comment by PieterjanRobbe** [comment]
The dependency on `Plots.jl` is now gone, see 1158ed8d317638935048ee65f79db9ba6938e343.

**Comment by giordano** [comment]
That is awesome, thanks!  Loading time of the package is down on my machine from 10 seconds to 2.8 seconds!

I saw that you're still using Plots for testing.  If you want to avoid that, you can either try [`VisualRegressionTests.jl`](https://github.com/JuliaPlots/VisualRegressionTests.jl) or look at what I do in [`Measurements.jl`](https://github.com/JuliaPhysics/Measurements.jl/blob/2ef7fadf7c2644408cff555781b9c10adfca26f6/test/plots.jl) without using extra packages :wink:

**Comment by giordano** [comment]
Last request: would you mind releasing a new version so that I can use a stable version?  Thanks!

**Comment by PieterjanRobbe** [comment]
Sure, I'll try to remove the `Plots.jl` dependency for testing, and release a new version afterwards.

**Comment by giordano** [comment]
I saw the new release, thanks!

**Comment by PieterjanRobbe** [comment]
You're welcome. Let me know if you would experience any other issues!
