### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by juliohm** [PieterjanRobbe/GaussianRandomFields.jl#24]
Hi @PieterjanRobbe , this is an incredible package, thank you for your work. I really like that you're interested in simulating Gaussian fields over finite element meshes, that is pretty much what a bunch of my packages are trying to achieve:

- [Direct or LU simulation](https://github.com/JuliaEarth/DirectGaussianSimulation.jl)
- [Spectral simulation](https://github.com/JuliaEarth/SpectralGaussianSimulation.jl)
- [Sequential simulation](https://github.com/JuliaEarth/KrigingEstimators.jl/blob/master/src/solvers/sgsim.jl)

I wonder if I could migrate these solvers to GaussianRandomFields.jl if they are not yet available, and if we could join efforts on a single package/repository to achieve this ultimate goal.

Could you elaborate on the mesh types supported? I am trying to formalize some of this work in the GeoStats.jl stack, and it would be really nice if we could work more closely to not only be able to simulate Gaussian fields, but other kinds of spatial random fields on spatial domains.

**Comment by juliohm** [comment]
Oh I noticed that I've opened a similar issue a long time ago asking about joining efforts: https://github.com/PieterjanRobbe/GaussianRandomFields.jl/issues/3 My memory is failing me.

This time however I am wondering if I should migrate my solvers to GaussianRandomFields.jl given that it is evolving nicely. I will leave the issue open for a few more days.

**Comment by PieterjanRobbe** [comment]
Hi @juliohm, thank you. Those seem to be some interesting packages you've got there. There is definitely room to improve on the solvers in GaussianRandomFields.jl, so feel free to add them to this package as you see fit. As far as simulating Gaussian random fields on finite element meshes, currently, only Cholesky factorisation and spectral methods are implemented. I thought for some time to extend the KL expansion with Nyström quadrature to be able to simulate on arbitrary domains, but it seemed to difficult at that time. (At the very least, this requires you to generate quadrature points on the specified domain). The interface for meshes is also very basic, if I recall correctly it requires only a node and element table. Could you give an example of the spatial random fields you would be interested in?

**Comment by juliohm** [comment]
Hi @PieterjanRobbe, 

> Could you give an example of the spatial random fields you would be interested in?

Most random fields we've been generating represent spatial properties of the subsurface for applications in hydrogeology, petroleum, geothermal, mining, ... More recently, we got involved in some projects where we need to simulate climate conditions (2D meshes with temperature, precipitation, etc.) It is a lot of fun :)

Perhaps I should clarify the scope of GeoStats.jl so that you can decide if it makes sense to merge these packages in a single repository. The stack contains a bunch of solvers for simulating spatial properties over meshes that you can find here: https://juliaearth.github.io/GeoStats.jl/stable/solvers/ The Gaussian solvers I linked above could be migrated to GaussianRandomFields.jl for example if you feel that the project is heading towards similar goals. The major challenge would be to align terminology (e.g. variogram vs. covariance) and to refactor the solvers using a common API.

Let me ask you... How do you feel about adding a dependency such as GeoStatsBase.jl to GaussianRandomFields.jl? What use cases do you have in mind for the project?

I think we have two options moving forward:

1. I can migrate the solvers I mentioned to GaussianRandomFields.jl and we can keep working in the repo together, either here or in the organization if you are ok with that.
2. Or I can start another package in JuliaEarth with the solvers we currently have there and develop this package separately from GaussianRandomFields.jl

Please let me know what do you think is the best option, and I can work on it in the next weeks.

**Comment by PieterjanRobbe** [comment]
Hi @juliohm, indeed, that sounds like a lot of fun! I'm working on numerical analysis myself, so the random fields I use do not necessarily represent something physical per se. The random field generation was just a small part of the challenge in the project I was working on, and as such I don't have any concrete plans to add more solvers. I'm just a bit sceptical of having this package depend directly on GeoStatsBase.jl, since there are perhaps other users of GaussianRandomFields.jl that have a different application in mind? So I think option 2 would be the cleanest way to move forward here. You could generate a package in the GeoStats universe that is tailored for Gaussian random field generation/simulation, and that links to the correct solvers for Direct/Sequential/SpectralGaussianSimulation/GaussianRandomFields? This is perhaps the most portable way for the future, and I would be happy to contribute to such a project!

**Comment by juliohm** [comment]
Hi @PieterjanRobbe , sounds good. I will try to create another package in JuliaEarth to put together those packages, and will see to what extent we could interop or leverage the code in GaussianRandomFields.jl. Worst case scenario we copy/paste stuff around to provide geomodelers with what they need more easily. Gaussian fields are a lot of fun.

I will close this issue for now. :+1:
