### ISSUE TITLE
Join efforts?

### ISSUE THREAD

**Issue by juliohm** [PieterjanRobbe/GaussianRandomFields.jl#3]
Just sharing a project that I've been working on for a while now that addresses not only Gaussian fields, but stochastic processes in general: https://github.com/juliohm/GeoStats.jl

It would be great to have other researchers joining the effort. I am planning to generalize the Kriging-based solvers after Julia v0.7 is out and to support multiple levels of parallelism. If you are interested, please reach out. Feel free to close the issue anytime.

Best,

**Comment by PieterjanRobbe** [comment]
I don't have experience using Kriging techniques myself, but I'd be happy to share my knowledge with Gaussian random fields so far!

**Comment by juliohm** [comment]
Kriging is the most general form of covariance-based estimators. For historical reasons two communities worked separately on the same topic, and what is known today as Gaussian Processes (the method) is a specific case of Kriging, there is [this notebook](http://nbviewer.jupyter.org/github/juliohm/GeoStats.jl/blob/master/examples/GaussianProcesses.ipynb) giving an example.

I see two ways that we can join efforts to benefit the community.

### Strategy 1

In the first option you could integrate your Gaussian process solver in the framework as described [here](https://github.com/juliohm/GeoStatsBase.jl) and [here](https://github.com/juliohm/GeoStatsDevTools.jl). In a nutshell, you just need to write a single function in your package called `solve` that takes an estimation (or simulation) problem as the first argument and your Gaussian process solver as the second, performs estimation (or simulation) using any functions you already implemented, and outputs a flattened solution (e.g. 2D grid flattened into 1D vector).

### Strategy 2

In a second option, I have written the Kriging solver in GeoStats.jl that already does estimation over arbitrary domain types (i.e. regular grids, point collections, meshes). The corresponding simulation version is called SeqGaussSim, but both these solvers need improvements after Julia v0.7 is out. These covariance systems can be quite ill-conditioned depending on the data configuration (specially with Gaussian kernels). If you feel comfortable with what the code is doing, there are lots of fixes and optimizations to do.

In either case, please don't hesitate to reach out on gitter: https://gitter.im/JuliaEarth/GeoStats.jl My goal with GeoStats.jl is to make it possible for researchers to switch between various estimation/simulation solvers without having to learn new syntax. You can also do fun stuff like cross-validation in [this example](http://nbviewer.jupyter.org/github/juliohm/GeoStats.jl/blob/master/examples/SolverComparison.ipynb).

I will check what you have implemented to see how we can get the best of both worlds.

**Comment by juliohm** [comment]
I will close the issue and let you decide if you want to proceed with any of the options above. In any case, thanks for contributing a package for GPs, you might also find GaussianProcesses.jl useful for your work/research: https://github.com/STOR-i/GaussianProcesses.jl

Best,
