### ISSUE TITLE
Method of computation on mesh

### ISSUE THREAD

**Issue by rleegates** [PieterjanRobbe/GaussianRandomFields.jl#4]
I am wondering - is the KL expansion computed as an integral over the mesh, or is the KL expansion computed on a bounding box and then evaluated the nodes?

**Comment by PieterjanRobbe** [comment]
Hi Robert, I implemented a bounding box method for the computation of the integral equation. You can see this in [karhunen_loeve.jl](GaussianRandomFields.jl/src/generators/karhunen_loeve.jl) on line 77. I can pass some pointers to literature in case you are interested.

**Comment by rleegates** [comment]
Hi Pieterjan, thanks for the great package and thanks for the quick reply!  Yes, I would be interested in some literature. I may be mistaken, but I was of the opinion that the eigenfunctions in the KL expansion depend on the geometry of the body, see e.g. [Keese, A.: Numerical solution of systems with stochastic uncertainties - a general purpose framework for stochastic finite elements. PhD thesis. Technische Universität Braunschweig. 2004. p. 41](https://publikationsserver.tu-braunschweig.de/servlets/MCRFileNodeServlet/dbbs_derivate_00001595/Document.pdf). If this is the case, perhaps it should be mentioned in the documentation.

**Comment by PieterjanRobbe** [comment]
Thanks for the reference. I implemented the KL expansion using the Nyström method, you can find more details [here](https://www.sciencedirect.com/science/article/pii/S0045782513003502). I used the KL expansion on a finite element mesh with ~4M nodes, and the bounding box method made the eigenvalue problem feasible. However, you can compute the integral over the mesh by using the `Spectral()` option, and put the number of eigenvalues `n` to the requested number of terms. I tried to make this a bit more clear in the code and the docs. The tutorial is also updated. Here's the L-shape example from your reference:
![screen shot 2018-03-09 at 15 21 08](https://user-images.githubusercontent.com/15999604/37214585-c29e6508-23b5-11e8-8726-e647eaf106d4.png)
Feel free to make further suggestions!

**Comment by rleegates** [comment]
Perfect! Thank you for clarifying. Shouldn't the Nyström method also work (and be efficient) for general domains?

**Comment by PieterjanRobbe** [comment]
Definitely. Either you have to evaluate the covariance matrix on the complete mesh, or you do random sampling inside the domain of interest to get the quadrature nodes. Depending on the size of the mesh, the first approach might be infeasible. (At least, that's what I observed in my use case, so I opted for a bounding box approach). If you're interested, I can take look and implement the non-bounding box KL for the FE case as well. Or, feel free to submit a pull request yourself ;)
