### ISSUE TITLE
unstructured meshes

### ISSUE THREAD

**Issue by qxj233333** [PieterjanRobbe/GaussianRandomFields.jl#46]
Great work
I'm interested in the construction of irregular regions
But I don't know the meaning of element in Lshape and star（fem_data）
Can you help me out
Thanks

**Comment by PieterjanRobbe** [comment]
This is using the default convention in FEM:
```
points, elements = star()
```
gives you a `720 x 2` matrix `points` with node coordinates (one node for each row), and a `1284 x 3` matrix `elements` with element connectivities. Each row in `elements` defines a 2D finite element by connecting three nodes, and the indices on each row tell you which nodes are connected.
