### ISSUE TITLE
Broadcast behavior of CovarianceStructure

### ISSUE THREAD

**Issue by AndreConsidera** [PieterjanRobbe/GaussianRandomFields.jl#48]
Hi there, nice package btw.  I found that the following piece of code  does not work: 

```
e  = Exponential(.5) 
x = 0:0.1:1
apply.(e, x)

ERROR: MethodError: no method matching length(::Exponential{Float64})
```
I think this is undesirable when trying to plot for visualization purposes
```
plot(x, apply.(e, x))
```

The following  broadcast behavior might do the trick:

`Base.broadcastable(c::CovarianceStructure) = Ref(c)`

Best,

**Comment by PieterjanRobbe** [comment]
Thanks!  I've added a plot recipe, so now you can do
```julia
plot(x, e)
```

And also
```julia
νs = range(0.5, stop=2, step=0.25)
plot([x -> apply.(Matern(1, ν), x) for ν in νs], palette=:darktest, label=reshape(["ν = $ν" for ν in νs], (1, length(νs))))
```
<img width="590" alt="Screenshot 2023-05-26 at 21 38 40" src="https://github.com/PieterjanRobbe/GaussianRandomFields.jl/assets/15999604/9726cfb9-408e-4bec-ae64-4ab0921872f3">
