### ISSUE TITLE
Play nicely with Plots.jl

### ISSUE THREAD

**Issue by ajdunlap** [PieterjanRobbe/GaussianRandomFields.jl#5]
It would be nice if there were a Plots.jl recipe for GaussianRandomFields.

**Comment by PieterjanRobbe** [comment]
True. At the time of writing, I was only familiar with the PyPlots syntax. It should be straightforward to adapt src/plot.jl to cover Plots.jl. I'll have a look at this later this month!

**Comment by PieterjanRobbe** [comment]
I remember now why I chose PyPlot.jl over Plots.jl: integration with Plots.jl works nicely for 1d/2d plotting, including surface/contour plots, but as far as I can see, proper implementation for triangular meshes and patches is still lacking (see [#392](https://github.com/JuliaPlots/Plots.jl/issues/392) and [#31](https://github.com/jheinen/GR.jl/issues/31)). Now I'm unsure if I should link with Plots.jl, and give up a few plotting features, or just wait until these features are implemented. This is the "star" example from the tutorial...
![figure_1](https://user-images.githubusercontent.com/15999604/42220832-6fba750e-7ed0-11e8-8e53-ea6229b62a9b.png)

**Comment by PieterjanRobbe** [comment]
Fixed with 678c847826377e430e7e7f6aa0989bc67fecf946!
