### ISSUE TITLE
Smooth low-rank approximation of random field with karhunen loeve

### ISSUE THREAD

**Issue by baxmittens** [PieterjanRobbe/GaussianRandomFields.jl#54]
Hello all,

first of all, I think you provided an excellent package here. Thank you for your work.
I have a problem using it. I'll try to describe.

The following code 
```julia
using GaussianRandomFields
using Plots
import PlotlyJS
cov = CovarianceFunction(1, Exponential(.5))
pts_10 = range(0, stop=2, length=10)
pts_100 = range(0, stop=2, length=100)
grf_KL_10_p_10 = GaussianRandomField(cov, KarhunenLoeve(10), pts_10) # KL with 10 modes and 10 points
grf_KL_10_p_100 = GaussianRandomField(cov, KarhunenLoeve(10), pts_100) # KL with 10 modes and 100 points
grf_KL_100_p_100 = GaussianRandomField(cov, KarhunenLoeve(100), pts_100)# KL with 100 modes and 100 points
PlotlyJS.plot(PlotlyJS.GenericTrace[
        PlotlyJS.scatter(y=grf_KL_10_p_100.data.eigenfunc[:,1], x=pts_100,name="KL_10_p_100"), # this looks strange
        PlotlyJS.scatter(y=grf_KL_10_p_10.data.eigenfunc[:,1], x=pts_10,name="KL_10_p_10"),
        PlotlyJS.scatter(y=grf_KL_100_p_100.data.eigenfunc[:,1], x=pts_100,name="KL_100_p_100"),
        ]
        ) 
```
produces this image (KL_10_p_10 and KL_100_p_100 are looking fine)
![image](https://github.com/PieterjanRobbe/GaussianRandomFields.jl/assets/100423479/8ef77d0f-a48c-445d-b52b-1a8e011ee95d)
which looks strange.

The following code 
```julia
xi = randn(randdim(grf_KL_10_p_100))
PlotlyJS.plot(PlotlyJS.GenericTrace[
        PlotlyJS.scatter(y=sample(grf_KL_10_p_100,xi=xi),x=pts_100,name="KL_10_p_100"),
        PlotlyJS.scatter(
            y=(repeat(xi',100,1).*grf_KL_100_p_100.data.eigenfunc[:,1:10])*sqrt.(grf_KL_100_p_100.data.eigenval[1:10]), 
            x=pts_100, 
            name="Random field generated by 10 modes from KL_100_p_100"
        )
    ]
    )
```
produces this image

![image](https://github.com/PieterjanRobbe/GaussianRandomFields.jl/assets/100423479/be894e5d-3da7-4dd0-b976-cfc35539aa85)

of how the random field generated from `KL_10_p_100` looks like and versus how I think the random field should look like.

Am I using the package wrong or is there some strange?

Additionally:
I am not sure if things like
```julia
GaussianRandomField(cov, KarhunenLoeve(500), pts_100)
```
should work in general. Why can I generate a KL with 500 terms while I only provided a discretization with 100 DOFs?

Greetz Max

**Comment by PieterjanRobbe** [comment]
Hi Max,

What you're observing are numerical issues with the computation of the eigenvalues and eigenfunctions/vectors. We use the [Nyström method](https://en.wikipedia.org/wiki/Nystr%C3%B6m_method) to solve the generalized eigenvalue problem. A poor choice of quadrature points can lead to very strange results, as you observe. There's a note about this in the documentation for `KarhunenLoeve`:
```
julia> ?KarhunenLoeve
[...]
  │ Note
  │
  │  Techniqually, the KL expansion is computed using the Nystrom method. For nonstructured grids, we use a bounding box approach. Try
  │  using the Spectral method if this is not what you want.

  │ Warning
  │
  │  To avoid an end effect in the eigenvalue decay, choose nq^d ≥ 5n.
[...]
```
The "end effect" causes the unexpected shape of the eigenfunction (and sample of the random field) computed with only 10 terms (= 10 quadrature points in 1D), and evaluated in 100 points. To avoid this, you can specify the keyword `nq = 50`, as recommended in the documentation. This should solve both of the issues you're observing.

You can also observe convergence with respect to the eigenvalues with increasing `nq` as follows:
```julia
julia> p = plot()

julia> for f in 1:5
           plot_eigenvalues!(GaussianRandomField(cov, KarhunenLoeve(10), pts_100, nq=10f), label="nq=$(10f)")
       end

julia> display(p)
```
This gives the following result:
<img width="913" alt="Screenshot 2023-10-24 at 4 36 48 PM" src="https://github.com/PieterjanRobbe/GaussianRandomFields.jl/assets/15999604/7a5db85d-a456-4fb0-b71f-34e3f6e3166b">

Finally, yes, you can generate a random field with more terms than discretization points, thanks to the Nyström method. In your case, using
```julia
grf_500_terms = GaussianRandomField(cov, KarhunenLoeve(500), pts_100)
```
the eigenfunctions will be generated in 500 equidistant points. The first 100 eigenvalues of that random field should agree with the eigenvalues of a field with 100 terms (provided that `nq` is large enough)
```julia
grf_100_terms = GaussianRandomField(cov, KarhunenLoeve(100), pts_100)
grf_100_terms_nq_500 = GaussianRandomField(cov, KarhunenLoeve(100), pts_100, nq=500)
```

```julia
julia> sum((grf_500_terms.data.eigenval[1:100] - grf_100_terms.data.eigenval).^2)
0.0012606162038396264

julia> sum((grf_500_terms.data.eigenval[1:100] - grf_100_terms_nq_500.data.eigenval).^2)
3.084966813077784e-11
```

**Comment by baxmittens** [comment]
Hi Pieterjan,

thank you for your quick response.

The nq keywords fixed the issues for me. I missed that while reading the docs.

I still cannot wrap my head around how  things like
```julia
grf500 = GaussianRandomField(cov, KarhunenLoeve(500), pts_100, nq=500)
```
should work since the resulting matrix grf500.data.eigenfunc is of size 100x500, and with 100 points in space, it is not possible to represent the 500th mode properly.
But for my use-case, I will always use way fewer modes than discretization points.

So thank you again. I close this one.

Greetz max

**Comment by PieterjanRobbe** [comment]
Great! You may be interested in reading section 3.2 in the reference below for more details on how this works.
> Betz, W., Papaioannou, I., & Straub, D. (2014). Numerical methods for the discretization of random fields by means of the Karhunen–Loève expansion. Computer Methods in Applied Mechanics and Engineering, 271, 109-129.

**Comment by baxmittens** [comment]
@PieterjanRobbe 
I read this and I know the theory in general. But I don't see why this should work. 

I played around with it a little bit
```julia
nq = 4000
grf_KL_500_p_100 = GaussianRandomField(cov, KarhunenLoeve(200), pts_100, nq=nq) # KL with 500 modes and 100 points
grf_KL_500_p_500 = GaussianRandomField(cov, KarhunenLoeve(200), pts_500, nq=nq) # KL with 500 modes and 500 points
grf_KL_500_p_1000 = GaussianRandomField(cov, KarhunenLoeve(200), pts_1000, nq=nq) # KL with 500 modes and 1000 points2
grf_KL_500_p_2000 = GaussianRandomField(cov, KarhunenLoeve(200), pts_2000, nq=nq) # KL with 500 modes and 2000 points
```
I set nq to different values ranging from 200 to 10_000
The outcome was like I did expect, independent of nq

Here is the 60th eigenfunction for the case generated with a discretization with 100 points

![image](https://github.com/PieterjanRobbe/GaussianRandomFields.jl/assets/100423479/b26512e0-e7f4-4089-9778-db19a7d070a7)

while it should look like something like this

![image](https://github.com/PieterjanRobbe/GaussianRandomFields.jl/assets/100423479/fae541d0-43dd-4812-a624-3ad997455273)

the 200th for 100 points looks like this

![image](https://github.com/PieterjanRobbe/GaussianRandomFields.jl/assets/100423479/450d228a-b6f1-486c-9c71-2e1b65b94a88)

while for 2000 points it looks like this

![image](https://github.com/PieterjanRobbe/GaussianRandomFields.jl/assets/100423479/58309cbf-7153-4c77-b268-cc55ec83556d)

I could imagine that both solutions are approximately correct in a sense of integrals but only the last one is the proper solution.

I would guess that in 1d, you need at least twice as many discretization points in space as KL-modes you want to display (something connected to the sampling theorem) in order to represent your eigenfunction in a sensible way.

But that is only a guess. What do you think?

**Comment by PieterjanRobbe** [comment]
That's just an aliasing effect. You're plotting discrete approximations to the continuous eigenfunction, represented with only a limited number of grid points. Here's an example representing the 6th eigenfunction with 5 and 100 grid points:

```julia
grf_KL_6_p_5 = GaussianRandomField(cov, KarhunenLoeve(6), range(start=0, stop=1, length=5), nq=100)
grf_KL_6_p_100 = GaussianRandomField(cov, KarhunenLoeve(6), range(start=0, stop=1, length=100), nq=100)
plot_eigenfunction(grf_KL_6_p_100, 6, label="100 points", legend = :outertopright)
plot_eigenfunction!(grf_KL_6_p_5, 6, label="5 points", markershape=:circle, markerstrokewidth=0)
```
gives
<img width="1231" alt="Screenshot 2023-10-25 at 3 15 08 PM" src="https://github.com/PieterjanRobbe/GaussianRandomFields.jl/assets/15999604/18ba930c-d778-4d7e-873c-15d1c86f43b3">

(Note: you may need to generate the random field several times, the orientation of the eigenfunctions is not guaranteed to be the same).

**Comment by baxmittens** [comment]
That is exactly what I was describing.
But this is not just an aliasing effect. As you can clearly see, you are missing "frequencies".
Your discretization is just not able to represent those high-frequency modes.
Your resulting random field will not necessarily satisfy the desired properties.
Surely, this is not an error or something like that on your side. That is just a thing the user has to be aware of.

**Comment by baxmittens** [comment]
The `i`-th (i=0,...,n) eigenfunction for an exponential kernel in 1d has the property that it has exactly `i` zero crossing. 
A property of the coarse-scale solution is missing here, and thus, there is no proper approximate solution.
I would like at least a warning in that case...or a hint in the documentation if you do not want that under any circumstances.

**Comment by PieterjanRobbe** [comment]
You can consider creating a PR with a proposal for a documentation change.

**Comment by baxmittens** [comment]
I'll do it on one of the following days.
It is really just a minor thing but I think it could be a useful addition for some users.
have a great day and thank you for responding once again.
