### ISSUE TITLE
Question for defining custom covariance function

### ISSUE THREAD

**Issue by zkk960317** [PieterjanRobbe/GaussianRandomFields.jl#64]
First, why the apply function of exponential ` apply(e::Exponential, x::Real) = e.σ * e.σ * exp(-x / e.λ)` has two ` e.σ ` multiplied, this is different from the original definition.
Then, if I have a custom function ``C(x, y) = σ * exp(-ρ / λ) + r``, the apply function should be `e.σ * e.σ * exp(-x / e.λ) +e.r` or `e.σ * (e.σ * exp(-x / e.λ) +e.r)`?
Looking forward to your answer. @PieterjanRobbe

**Comment by zkk960317** [comment]
@PieterjanRobbe Thank you, I think I got it. The problem is that the description of function in the line 24 in `exponential.jl` should also be modified to match the source code. The same problem exists with other covariance functions.

**Comment by PieterjanRobbe** [comment]
Thanks for pointing this out! I've updated the documentation and tutorial to reflect the changes.
