### ISSUE TITLE
New release to aid in compat satisfiability

### ISSUE THREAD

**Issue by odunbar** [PieterjanRobbe/GaussianRandomFields.jl#65]
## Issue

Hi @PieterjanRobbe Thanks for the great package! Unfortunately we are having some compat issues with FastGaussQuadrature being restricted to v0.5. Is this (in particular < v1) required? 

If not could we request the relevant compat be updated to `"0.5, 1"` and that you push a new tagged release for this? 

Thanks again! 

PS a [quick link](https://clima.github.io/EnsembleKalmanProcesses.jl/dev/examples/darcy/) to an example using your fields :)

**Comment by PieterjanRobbe** [comment]
Hi @odunbar, thanks for your interest in this package!

Should be good as soon as [https://github.com/JuliaRegistries/General/pull/114375](https://github.com/JuliaRegistries/General/pull/114375) gets merged.

**Comment by odunbar** [comment]
Wonderful, thanks for your speed on this, I'll close the issue
